import Head from "next/head";

import logo from "../assets/logoipsum-287.svg";
import Image from "next/image";
import ResuableModal from "../shared/components/modal";
import { pageData } from "./api/dummydata";
import Link from "next/link";
import { useCountdown } from "../useCountdown";
import { useState } from "react";

export default function Home() {
  const [openModal, setOpenModal] = useState(false);
  const [days, hours, minutes, seconds] = useCountdown();
//@ts-ignore
  const DateTimeDisplay = ({ value, type }) => {
    return (
      <div>
        {type}
        <br />
        {value}
      </div>
    );
  };
  //@ts-ignore
  const ShowCounter = ({ days, hours, minutes, seconds }) => {
    return (
      <div className="countDown">
        <DateTimeDisplay type={"Days"} value={days} />

        <DateTimeDisplay type={"Hours"} value={hours} />

        <DateTimeDisplay type={"Minutes"} value={minutes} />

        <DateTimeDisplay type={"Seconds"} value={seconds} />
      </div>
    );
  };
  //@ts-ignore
  const CountdownTimer = ({ targetDate }) => {
    const [days, hours, minutes, seconds] = useCountdown(targetDate);
    return (
      <ShowCounter
        days={days}
        hours={hours}
        minutes={minutes}
        seconds={seconds}
      />
    );
  };
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="content">
        <div className="inner-content">
          <div className="column float-left">
           
            {/* <CountdownTimer targetDate={'01012025'}/> */}
            <h1>Lorem Ipsum</h1>
            <p>sub text</p>
          </div>
          <div className="column float-right">
            <Image
            alt="state"
            src={logo}
            width={300}
            height={250}
            />
          </div>  
        </div>
       </section> 
     
      <aside className="content">
        <h2>h2 lorem ipsum</h2>
        <p>aside section context</p>
      </aside>
    </>
  );
}
