import Head from "next/head";
import { useRouter } from "next/router";
import { pageData } from "../../api/dummydata";
import Image from "next/image";
import PageCard from "@/shared/components/pageCard";
export default function Service() {
  const router = useRouter()
  const pages = router.asPath.split('/')
  const page1 = pages[1].replace('%20', ' ').replace('-', ' ')
  const page = pages[2].replace('%20', ' ').replace('-', ' ')
  //@ts-ignore
  const pageDetails = pageData.filter((x) => x.name === page1); 
  const itemDetails = pageDetails[0]?.items.filter((x) => x.name === page)

  function sendToCart( item: any) {
    localStorage.setItem("Item", JSON.stringify(item));
    const existingItems: any[] = JSON.parse(localStorage.getItem("Cart")!) ?? [];
    existingItems?.push(item);
    localStorage.setItem("Cart", JSON.stringify(existingItems));
 
  }

  return (
    <>
      <Head>
        <title>{page} | details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        ></link>
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        ></link>
        <link rel="manifest" href="/site.webmanifest"></link>
      </Head>
        <section>    
            <div className="content">
                <h2>{page} h2</h2>
                <p>{itemDetails[0]?.name} p</p>    
            </div>
            <div className="content">
                <div className="inner-content">    
                    <div className="column"> 
                        <div className="detail-card">
                            <Image src={itemDetails[0]?.image} width={500} height={500} alt="product" />        
                        </div>
                    </div> 
                    <div className="column detail-details">
                        <div>
                            <p>{itemDetails[0]?.name}</p>
                            <p>{itemDetails[0]?.description}</p>
                            <p>${itemDetails[0]?.cost}</p>
                            <button type="button" onClick={() => sendToCart(itemDetails[0])}>Add to cart</button>
                        </div>
                    </div>
                </div>                 
            </div>      
        </section>
    </>
  );
}

function sendToCart() {
    throw new Error("Function not implemented.");
}

